// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

SEXP HandMadeKalmanFilterConstantCoeffCpp(NumericVector a0, NumericMatrix P0, NumericMatrix T, NumericMatrix Z, NumericMatrix HH, NumericMatrix GG, NumericMatrix yt);
List rcpp_hello_world();
SEXP test01();
SEXP testHMKF01();
SEXP testConvertFromArrayToVectorXd(NumericVector x);

static bool validateExported(const std::string& sig) {
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("SEXP(*HandMadeKalmanFilterConstantCoeffCpp)(NumericVector,NumericMatrix,NumericMatrix,NumericMatrix,NumericMatrix,NumericMatrix,NumericMatrix)");
        signatures.insert("List(*rcpp_hello_world)()");
        signatures.insert("SEXP(*test01)()");
        signatures.insert("SEXP(*testHMKF01)()");
        signatures.insert("SEXP(*testConvertFromArrayToVectorXd)(NumericVector)");
    }
    return signatures.find(sig) != signatures.end();
}

RCPP_MODULE(HandMadeKalmanFilter_RcppExports) {
    Rcpp::function("HandMadeKalmanFilterConstantCoeffCpp", &HandMadeKalmanFilterConstantCoeffCpp, Rcpp::List::create(Rcpp::Named("a0"), Rcpp::Named("P0"), Rcpp::Named("T"), Rcpp::Named("Z"), Rcpp::Named("HH"), Rcpp::Named("GG"), Rcpp::Named("yt")));
    Rcpp::function("rcpp_hello_world", &rcpp_hello_world, Rcpp::List::create());
    Rcpp::function("test01", &test01, Rcpp::List::create());
    Rcpp::function("testHMKF01", &testHMKF01, Rcpp::List::create());
    Rcpp::function("testConvertFromArrayToVectorXd", &testConvertFromArrayToVectorXd, Rcpp::List::create(Rcpp::Named("x")));
    Rcpp::function("RcppExports_validateExported", &validateExported);
}
